# Generated by Django 6.0 on 2026-01-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cart', '0003_order_address_order_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
